# Generated by Django 3.0.2 on 2020-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotmodel',
            name='colour',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
